// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.jetbrains.kotlin.jvm) apply false
    alias(libs.plugins.google.gms.google.services) apply false
    alias(libs.plugins.google.firebase.crashlytics) apply false
    alias(libs.plugins.google.firebase.perf) apply false
    alias(libs.plugins.google.firebase.appdistribution) apply false
    alias(libs.plugins.kover)
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.kotlin.kapt) apply false
}

buildscript {
    dependencies {
        classpath(libs.hilt.android.gradle.plugin)
    }
}

kover {
    reports {
        filters {
            excludes {
                classes(
                    "**.model.**",
                    "**.di.**",
                    "**.exception.**",
                    "**.exceptions.**",
                    "**.mapper.**",
                    "**.ui.**",
                    "**.design_system.**",
                    "**.entity.**",
                    "**.local.**",
                    "**.safe_image_viewer.**",
                    "**.build.**",
                    "dagger.hilt.internal.aggregatedroot.codegen.*",
                    "hilt_aggregated_deps.*",
                    "*_HiltModules*",
                    "**HiltModules**",
                    "*Hilt_*",
                    "*_Factory*",
                    "*BuildConfig*",
                    "**/*_AutoGenerated*",
                    "**/*_Impl*",
                    "**/*_Binder*",
                    "**/*_Component*"
                )
            }
        }
        total {
            verify {
                rule {
                    minBound(80)
                }
            }
        }
    }
}

dependencies {
    kover(project(":remote"))
    kover(project(":domain"))
    kover(project(":repository"))
    kover(project(":viewmodel"))
    kover(project(":safe_image_viewer"))
}