name: Movio CD Pipeline

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate APK
        run: ./gradlew assembleRelease

      - name: Extract Release Notes
        id: release_notes
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B | sed 's/"/\\"/g' | tr -d '\n')
          TRUNCATED_MSG="${COMMIT_MSG:0:500}"
          echo "$TRUNCATED_MSG" > release_notes.txt
          echo "notes=$TRUNCATED_MSG" >> $GITHUB_OUTPUT
          echo "Release notes: $TRUNCATED_MSG"

      - name: Upload APK to Firebase App Distribution
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_AUTH_TOKEN }} \
            --groups "cairo_squad" \
            --release-notes-file release_notes.txt